GuestHouseApp/GuestHouseApp/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuestHouseApp.Models
{
    public class Country
    {
        public virtual int Id { get; set; }
        public virtual string Description { get; set; }
        public virtual int Active { get; set; }
        public virtual string UpdatedBy { get; set; }
        public virtual DateTime UpdatedOn { get; set; }
    }
}

GuestHouseApp/GuestHouseApp/Models/GovtIdCard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuestHouseApp.Models
{
    public class GovtIdCard
    {
        public virtual int Id { get; set; }
        public virtual string Description { get; set; }
        public virtual int Active { get; set; }
        public virtual string UpdatedBy { get; set; }
        public virtual DateTime UpdatedOn { get; set; }
    }
}

GuestHouseApp/GuestHouseApp/Models/MasterTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuestHouseApp.Models
{
    public class MasterTable
    {
        public virtual int Id { get; set; }
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        [EmailAddress]
        public virtual string Email { get; set; }
        public virtual GovtIdCard GovtIdCard { get; set; }
        public virtual string GovtIdNo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public virtual DateTime DateOfArr { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public virtual DateTime DateOfDep { get; set; }
        public virtual Country Country { get; set; }
        public virtual int NumberOfPerson { get; set; }
        public virtual string Remarks { get; set; }
        public  virtual PaymentMethod  PaymentMethod { get; set; }
        public virtual int Active { get; set; }
        public virtual string UpdatedBy { get; set; }
        public virtual DateTime UpdatedOn { get; set; }
    }
}

GuestHouseApp/GuestHouseApp/Models/PaymentMethod.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuestHouseApp.Models
{
    public class PaymentMethod
    {
        public virtual int Id { get; set; }
        public virtual string Description { get; set; }
        public virtual int Active { get; set; }
        public virtual string UpdatedBy { get; set; }
        public virtual DateTime UpdatedOn { get; set; }
    }
}

GuestHouseApp/GuestHouseApp/ViewModels/ReservationVM.cs
using GuestHouseApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GuestHouseApp.ViewModels
{
    public class ReservationVM
    {
        public virtual MasterTable MasterTable { get; set; }
        public virtual List<GovtIdCard> GovtIdCardList { get; set; }
        public virtual List<Country> CountryList { get; set; }
        public virtual List<PaymentMethod> PaymentMethodList { get; set; }
    }
}

GuestHouseApp/GuestHouseApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuestHouseApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GuestHouseApp/GuestHouseApp/Controllers/ReservationController.cs
using GuestHouseApp.Dal;
using GuestHouseApp.Models;
using GuestHouseApp.ViewModels;
using NHibernate.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuestHouseApp.Controllers
{
    public class ReservationController : Controller
    {
        // GET: Regervation
        public ActionResult BookingHistory()
        {
            List<MasterTable> data = new List<MasterTable>();
            using (var session = DataBaseSetting.openSession())
            {
                data = session.Query<MasterTable>()
                                        .Fetch(x=>x.GovtIdCard)
                                        .Fetch(x=>x.Country)
                                        .Fetch(x=>x.PaymentMethod)
                                        .OrderBy(x=>x.DateOfArr)
                                        .Where(x => x.Active == 1).ToList();
            }
            return View(data);
        }
        public ActionResult Create()
        {
            ReservationVM vm = new ReservationVM();
            using(var session = DataBaseSetting.openSession())
            {
                vm.GovtIdCardList = session.Query<GovtIdCard>().Where(x => x.Active == 1).ToList();
                vm.CountryList = session.Query<Country>().Where(x => x.Active == 1).ToList();
                vm.PaymentMethodList = session.Query<PaymentMethod>().Where(x => x.Active == 1).ToList();
            }
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReservationVM vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    throw new Exception("Please Fill all Mandatory Fields !!");
                }
                MasterTable model = new MasterTable
                {
                    FirstName=vm.MasterTable.FirstName,
                    LastName=vm.MasterTable.LastName,
                    Email=vm.MasterTable.Email,
                    GovtIdCard=new GovtIdCard { Id=vm.MasterTable.GovtIdCard.Id},
                    GovtIdNo=vm.MasterTable.GovtIdNo,
                    DateOfArr=vm.MasterTable.DateOfArr,
                    DateOfDep=vm.MasterTable.DateOfDep,
                    Country=new Country { Id=vm.MasterTable.Country.Id},
                    NumberOfPerson=vm.MasterTable.NumberOfPerson,
                    Remarks=vm.MasterTable.Remarks,
                    PaymentMethod=new PaymentMethod { Id=vm.MasterTable.PaymentMethod.Id},
                    Active=1,
                    UpdatedBy=vm.MasterTable.Email,
                    UpdatedOn=DateTime.Now
                };
                using (var session = DataBaseSetting.openSession())
                {
                    using (var tx = session.BeginTransaction())
                    {
                        session.Save(model);
                        tx.Commit();
                        TempData["message"] = "Your Booking is Confirmed !!";
                    }
                }
            }
            catch(Exception e)
            {
                TempData["message"]=e.Message;
                using (var session = DataBaseSetting.openSession())
                {
                    vm.GovtIdCardList = session.Query<GovtIdCard>().Where(x => x.Active == 1).ToList();
                    vm.CountryList = session.Query<Country>().Where(x => x.Active == 1).ToList();
                    vm.PaymentMethodList = session.Query<PaymentMethod>().Where(x => x.Active == 1).ToList();
                }
                return View(vm);
            }
            return RedirectToAction("BookingHistory");
        }
    }
}

GuestHouseApp/GuestHouseApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GuestHouseApp/GuestHouseApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GuestHouseApp/GuestHouseApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home - Guest House Reservation App";
}
<style>
    img {
        height: 400px;
        max-height: 400px;
    }
</style>
<div class="jumbotron">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Images/room1.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Images/ignou1.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Images/ignou2.jpeg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<br />
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">About Us</h2>
        </div>
        <div class="card-body">
            <p>
                The Indira Gandhi National Open University (IGNOU), established by an Act of Parliament in 1985, has continuously striven to build an inclusive knowledge society through inclusive education. It has tried to increase the Gross Enrollment Ratio (GER) by offering high-quality teaching through the Open and Distance Learning (ODL) mode.
            </p>
            <p><a class="btn btn-default" href="http://www.ignou.ac.in/ignou/aboutignou/profile/2">More Info &raquo;</a></p>
        </div>
    </div>
</div>
<br />
<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Twitter Timeline</h2>
            </div>
            <div class="card-body">
                <a class="twitter-timeline" data-lang="en" data-height="500" data-theme="dark" href="https://twitter.com/OfficialIGNOU?ref_src=twsrc%5Etfw">Tweets by OfficialIGNOU</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Facebook Timeline</h2>
            </div>
            <div class="card-body">
                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FOfficialPageIGNOU&tabs=timeline&width=500&height=500&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="500" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
            </div>
        </div>
    </div>
</div>

GuestHouseApp/GuestHouseApp/Views/Reservation/BookingHistory.cshtml
@model IEnumerable<GuestHouseApp.Models.MasterTable>
@{
    ViewBag.Title = "BookingHistory";
}
@if (TempData["message"] != null)
{
    <br />
    <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <strong class="text-center">@TempData["message"]</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="col-12">
    <br />
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">Upcoming or Ongoing Guest Details<strong></strong></h3>
        </div>
        <div class="card-body table-responsive">
            @if (Model.Where(x => x.DateOfDep >= DateTime.Now.AddDays(-1)).Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Sl. No.</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Govt Issued-Id</th>
                        <th>Date of Arrival</th>
                        <th>Date of Departure</th>
                        <th>Country</th>
                        <th>Number of Persons</th>
                        <th>Special Requests</th>
                        <th>Payment Method</th>
                    </tr>
                    @{ int i = 0;}
                    @foreach (var item in Model.Where(x => x.DateOfDep >= DateTime.Now.AddDays(-1)))
                    {
                        i++;
                        <tr>
                            <td>@i</td>
                            <td>@item.FirstName</td>
                            <td>@item.LastName</td>
                            <td>@item.Email</td>
                            <td>
                                @item.GovtIdCard.Description
                                (@item.GovtIdNo)
                            </td>
                            <td>@item.DateOfArr.ToString("dd-MM-yyyy")</td>
                            <td>@item.DateOfDep.ToString("dd-MM-yyyy")</td>
                            <td>@item.Country.Description</td>
                            <td>@item.NumberOfPerson</td>
                            <td>@item.Remarks</td>
                            <td>@item.PaymentMethod.Description</td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    <h3 class="text-center">No Upcoming Guest</h3>
                </div>
            }

        </div>
    </div>
    <br />
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">Booking History <strong></strong></h3>
        </div>
        <div class="card-body table-responsive">
            @if (Model.Where(x => x.DateOfDep < DateTime.Now.AddDays(-1)).Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Sl. No.</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Govt Issued-Id</th>
                        <th>Date of Arrival</th>
                        <th>Date of Departure</th>
                        <th>Country</th>
                        <th>Number of Persons</th>
                        <th>Special Requests</th>
                        <th>Payment Method</th>
                    </tr>
                    @{ int i = 0;}
                    @foreach (var item in Model.Where(x => x.DateOfDep < DateTime.Now.AddDays(-1)))
                    {
                        i++;
                        <tr>
                            <td>@i</td>
                            <td>@item.FirstName</td>
                            <td>@item.LastName</td>
                            <td>@item.Email</td>
                            <td>
                                @item.GovtIdCard.Description
                                (@item.GovtIdNo)
                            </td>
                            <td>@item.DateOfArr.ToString("dd-MM-yyyy")</td>
                            <td>@item.DateOfDep.ToString("dd-MM-yyyy")</td>
                            <td>@item.Country.Description</td>
                            <td>@item.NumberOfPerson</td>
                            <td>@item.Remarks</td>
                            <td>@item.PaymentMethod.Description</td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    <h3 class="text-center">No Booking History</h3>
                </div>
            }

        </div>
    </div>
</div>

GuestHouseApp/GuestHouseApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .dropdown:hover .dropdown-menu{
            display:block;
            margin-top:0; /*remove the gap so it doesn't close*/
        }
    </style>
</head>
<body>
    <div class="container body-content bg-light">
        @*--------------Header Section start-----------------*@
        <br />
        <div style="max-height:250px;" class="row">
            <img src="~/Images/logo.png" alt="logo" style="height:80px;" class="col-2"/>
            <h3 class="col-8 text-center">IGNOU Guest House Reservation Application</h3>
            <img src="~/Images/ignou.png" alt="IGNOU Logo" class="col-2" style="height:80px;"/>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">GuestHouseApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Reservation
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="@Url.Action("Create","Reservation")">Book Room</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("BookingHistory","Reservation")">Booking History</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About","Home")">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @*--------------Header Section End-----------------*@
        @*--------------Body Section start-----------------*@
        @RenderBody()
        <hr />
        @*--------------Body Section End-----------------*@

        @*--------------Footer Section start-----------------*@
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year -Arvind (E.No.-2201112449) Guest House Reservation Application</p>
        </footer>
        @*--------------Footer Section End-----------------*@
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>